[package]
name = "oidc-filter"
version = "0.1.0"
authors = ["Daniel Grimm <dgrimm@redhat.com>"]
edition = "2018"

[dependencies]
proxy-wasm = "0.1.3"
log = "0.4.8"
url = "2.1.1"
serde_json = "1.0"
state = "0.4.1"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
